Module4 task1
htmlacademy-javascript/1265881-keksobooking-24 pull request #3
Opened 2021-10-02 15:54 UTC by IrinaLebedeva

2021-10-03 21:32 UTC, o-bender requested changes

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +Array.prototype.mixArr = function () {
Вообще я противник подобного подхода. Т.к. это не очевидно и несёт больше головной боли чем пользы.

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +const TEMPLATE_AVATAR_URL = 'img/avatars/user{{xx}}.png';
лучше напиши id вместо xx

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +  const getAvatarId = (currentAdvertId) => currentAdvertId < 10 ? `0${currentAdvertId}` : currentAdvertId;
а зачем тут функция?

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +const getTitle = (type) => `${DESCRIPTIONS[getRandomIntegerFromRange(0, DESCRIPTIONS.length - 1)]} ${type}`.capitalize();
Если уж совсем прикапываться, то по бизнес логике размер, формат, регистр и т.п. это дело либо контента, т.е. всё надо изначально сохранять в БД в правильном виде, либо это дело CSS. А вот в js капиталайзить, верный способ удивить себя через пару месяцев:)

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +      title: title,
по критериям надо: 
```
{
   title, // вместо title: title,
   somval: getSomeval(),
}
```

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +const advertCard = (advertId) => {
лучше createAdvertCard, так понятно, что это функция создающая карточку, а не объект карточки

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +const getDescription = (title, features) =>
лушче createDescription. Get это взять, получить. Но тут ты его создаёшь.

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +const getDescription = (title, features) =>
В getTitle, getAdvertCards, getAvatar тоже самое.

2021-10-03 21:32 UTC, o-bender commented on js/main.js
> +  const mockAdvertCards = [];
Такс, ну раз везде map и sort то тут тоже давай функциональщину используй)

2021-10-03 21:32 UTC, o-bender commented on js/utils/get-random-number.js
> +  minIsNotPositiveOrZeroNumber: 'Минимальное значение из диапазона не может быть меньше нуля',
В принципе тут можно текст сообщений сразу обернуть в ошибку:
```
const ERRORS = {
  minIsNotPositiveOrZeroNumber: new ValidationError('Минимальное значение из диапазона не может быть меньше нуля'),
```

2021-10-03 21:32 UTC, o-bender commented on js/utils/get-random-number.js
> +  if (!((fractionDigits >= 0) && (fractionDigits <= 100))) {
тут можно убрать лишние скобки и уйти от отрицания: fractionDigits < 0 || fractionDigits > 100
по критерию 0 и 100 надо вынести в константы

2021-10-04 13:46 UTC, IrinaLebedeva commented on js/main.js
> +Array.prototype.mixArr = function () {
т.е. стандартный набор методов расширять - это зло?

2021-10-04 13:47 UTC, IrinaLebedeva commented on js/main.js
> +const TEMPLATE_AVATAR_URL = 'img/avatars/user{{xx}}.png';
угу, просто из ТЗ так скопировала, вообще не подумала менять)

2021-10-04 13:54 UTC, IrinaLebedeva commented on js/main.js
> +  const getAvatarId = (currentAdvertId) => currentAdvertId < 10 ? `0${currentAdvertId}` : currentAdvertId;
)) в смысле? не поняла, про что ты, но могу без объявления getAvatarId сразу вернуть результат, однако меня смущают длинные конструкции, кажется, что читается плохо. Пока интуитивное чувство эстетики в js-коде не работает)

2021-10-04 13:54 UTC, IrinaLebedeva commented on js/main.js
> +const getTitle = (type) => `${DESCRIPTIONS[getRandomIntegerFromRange(0, DESCRIPTIONS.length - 1)]} ${type}`.capitalize();
давай, конечно, прикапывайся, я за этим и пришла)

2021-10-04 13:59 UTC, IrinaLebedeva commented on js/main.js
> +      title: title,
эм, не нашла, что это за критерий, но ок, исправлю)

2021-10-04 14:05 UTC, IrinaLebedeva commented on js/main.js
> +  const mockAdvertCards = [];
)) чего сделать то нужно?

2021-10-04 14:06 UTC, IrinaLebedeva commented on js/utils/get-random-number.js
> +  minIsNotPositiveOrZeroNumber: 'Минимальное значение из диапазона не может быть меньше нуля',
меня не оставляет мысль об интернационализации, ошибки на русском - это зло. но могу на англ. перевести и расслабиться)

2021-10-04 15:15 UTC, o-bender commented on js/main.js
> +Array.prototype.mixArr = function () {
Я не могу сказать, что это абсолютное зло. Полифилы на пример это хорошо. К примеру есть moment.js. Вот они не стали расширять прототип. Они просто просто сделали свой тип данных и все дела. В собственном типе можешь писать, что и как угодно и не беспокоиться о перекрытии имён, корявой инициализации или ещё чем-то подобном.

2021-10-04 15:19 UTC, o-bender commented on js/main.js
> +  const getAvatarId = (currentAdvertId) => currentAdvertId < 10 ? `0${currentAdvertId}` : currentAdvertId;
а во так:)
```
const getAvatar = (advertId) => {
  return TEMPLATE_AVATAR_URL.replace('{{xx}}', `0${advertId}`.slice(-2));
};
```

2021-10-04 15:24 UTC, o-bender commented on js/main.js
> +  const mockAdvertCards = [];
вот так:
```
const getAdvertCards = () => {
  return Array(ADVERTS_COUNT).fill(null).map((_, i) => advertCard(i+1));
};
```
Выделяем память под список из 10 элементов. Заполняем список null-ами. Проходим map-ом)

2021-10-04 15:25 UTC, o-bender commented on js/utils/get-random-number.js
> +  minIsNotPositiveOrZeroNumber: 'Минимальное значение из диапазона не может быть меньше нуля',
Отбрось эту мысль. Переключение языков это отдельная песня.

2021-10-04 18:56 UTC, IrinaLebedeva commented on js/main.js
> +  const getAvatarId = (currentAdvertId) => currentAdvertId < 10 ? `0${currentAdvertId}` : currentAdvertId;
неа, ADVERTS_COUNT может быть и 200

2021-10-04 18:57 UTC, IrinaLebedeva commented on js/main.js
> +  const mockAdvertCards = [];
кайф))

2021-10-04 19:33 UTC, IrinaLebedeva commented on js/utils/get-random-number.js
> +  minIsNotPositiveOrZeroNumber: 'Минимальное значение из диапазона не может быть меньше нуля',
хм, если new ValidationError() закидывать в константы, то создадутся экземпляры объектов ошибок, даже если они не понадобятся

2021-10-05 06:45 UTC, o-bender commented on js/main.js
> +  const getAvatarId = (currentAdvertId) => currentAdvertId < 10 ? `0${currentAdvertId}` : currentAdvertId;
ну ок:
```
const createAvatarURL = (advertID) => {
  const id = advertID < 10 ? `0${advertID}` : advertID;
  return TEMPLATE_AVATAR_URL.replace('{{xx}}', id);
};
```
Но если быть уж совсем честным, то я не оч понимаю зачем этот ноль вообще нужен:) и почему цифровой id превращается в строку. Обычно id это либо primary key из БД, либо uuid. Primary key это как правило целочисленное значение. А uuid хоть и строка, но это хэш.

2021-10-05 06:46 UTC, o-bender commented on js/utils/get-random-number.js
> +  minIsNotPositiveOrZeroNumber: 'Минимальное значение из диапазона не может быть меньше нуля',
Создадутся, выделят прям чуток-чуток памяти. Чуть больше чем просто строка. Зато в процессе работы не надо будет их создавать, тратить на это время и писать однотипный код.

2021-10-06 11:04 UTC, merged